-- 코드를 입력하세요
# USER_INFO : 회원ID, 성별, 나이, 가입일
# ONLINE_SALE : 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일

# 년, 월, 성별 별로 상품을 구매한 회원수 집계
# 오름차순으로 집계
# 성별정보가 없는 경우 제외

# USERS 필드만 수를 구함
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER